<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks App</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
</head>

<body>
    <header>
        <?php require_once 'resources/views/partials/navbar.phtml' ?>
    </header>

    <main class="container p-5 mx-auto">
        <div class="row">
            <div class="col-md-5">
                <div class="card">
                    <div class="card-body">
                        <form id="task-form">
                            <input type="hidden" id="taskId">
                            <div class="form-group">
                                <input class="form-control" type="text" id="name" placeholder="Insert task name">
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" id="description" cols="30" rows="10"
                                    placeholder="Insert description"></textarea>
                            </div>
                            <button class="btn btn-primary btn-block" type="submit">Add Tasks</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-7">

                <div class="card my-4" id="task-result">
                    <div class="card-body">
                        <ul id="container"></ul>
                    </div>
                </div>
                <div class="card-my-4" id="buttons">
                    <a class="btn btn-info task-refresh">Refresh</a>
                </div>
                <table class="table table-bordered table-responsive-sm">
                    <thead>
                        <tr>
                            <td>Id</td>
                            <td>Name</td>
                            <td>Description</td>
                        </tr>
                    </thead>
                    <tbody id="tasks"></tbody>
                </table>
            </div>
        </div>
    </main>

    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="js/app.js"></script>
</body>

</html>