<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container">
        <a href="#" class="navbar-brand pl-2"><img src="images/taskdemand_logo_large.png" alt=""></a>
        <ul class="navbar-nav mr-auto">
            <form class="form-inline my-2 my-lg-0">
                <input type="search" id="search" class="form-control" placeholder="Search task...">
                <button type="submit" class="btn btn-success">
                    Search
                </button>
            </form>
        </ul>
    </div>

</nav>