<nav class="navbar navbar-expand-lg navbar-light bg-info border-0">
    <div class="container">
        <a href="#" class="navbar-brand pl-2"><img src="images/taskdemand_logo_large.png" width="256" alt=""></a>
        <ul class="navbar-nav mx-auto">
            <form class="form-inline my-2 my-lg-0">
                <input type="search" id="search" class="form-control" placeholder="Search for task">
                <button type="submit" class="btn btn-sm-block btn-success">
                    Search
                </button>
            </form>
        </ul>
    </div>

</nav>