 <footer class="footer bg-dark text-white py-5">
     <div class="container-fluid pb-5">
         <div class="col-sm-12 col-md-12 col-lg-12">
             <p class="text-center font-weight-bold">Developed by
                 <a href="https://twitter.com/devkhris" class="text-decoration-none text-primary">
                     DevKhris
                 </a>
             </p>
         </div>
     </div>
 </footer>